# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb84a99d8624f43717633abc5a8ba9bbd8ef2f8d769a68e5631852f9346c889e32f28a730ef8ceb98eb9867d42c78734699f61079a1a262c01c54fa2f0937340

test:
  secret_key_base: e48400a603044ad7730320b963caaeaf3c7a441e963151b594b0936132c3442fb60e65258cf57800529d7276bed539865597a52900c2436d65b5801d7755dcaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
